version: '1.0.{build}'

environment:
  matrix:
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

configuration:
- Debug
- Release

platform: Any CPU

before_build:
  nuget restore

cache:
  - packages -> **\packages.config

build:
  parallel: true
  verbosity: minimal
