version: '2'

services:
  identity.api:
    image: identity.api
    build:
      context: ./src/Identity.api
      dockerfile: Dockerfile

  profile.api:
    image: profile.api
    build:
      context: ./src/Profile.api
      dockerfile: Dockerfile

  projects.api:
    image: projects.api
    build:
      context: ./src/Projects.api
      dockerfile: Dockerfile
