version: '2'

services:
  
  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet

  webui:
    image: cvpz/webui
    container_name: webui
    build:
      context: ./src/WebUI
      dockerfile: Dockerfile
    networks:
      - cvpz

  identity.api:
    image: cvpz/identity.api
    container_name: identity_api
    build:
      context: ./src/Identity.api
      dockerfile: Dockerfile
    links:
      - mongodb
    networks:
      - cvpz

  profile.api:
    image: cvpz/profile.api
    container_name: profile_api
    build:
      context: ./src/Profile.api
      dockerfile: Dockerfile
    links:
     - mongodb
    networks:
      - cvpz

  projects.api:
    image: cvpz/projects.api
    container_name: projects_api
    build:
      context: ./src/Projects.api
      dockerfile: Dockerfile
    links:
      - mongodb
    networks:
      - cvpz

networks:
  cvpz:
    driver: bridge