version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:latest
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./CVPZ.sln && dotnet publish ./CVPZ.sln -c Release -o ./obj/Docker/publish"
