version: '2'

services:

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  projects.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development